### ISSUE TITLE
Make MSC webscraper deterministic and validate collected data

### ISSUE THREAD

**Issue by EwoutH** [EwoutH/shipping-data#33]
Currently the MSC webscraper is not deterministic yet, each run it collects different data. A recent [CI run](https://github.com/EwoutH/shipping-data/actions/runs/3318542223/jobs/5482603899) even failed unexpectedly.

Ideally the webscrapper should be deterministic, if not feasible it should have the highest coverage of data possible. Validation should be done.

**Comment by thomassandbergen** [comment]
@EwoutH How did you find out that MSC webscraper gives different results based on the run?

If the problem is in the site itself, we might not be able to fix it. Maybe we can have a talk with @imvs95 if we should still use the data or we should just use the data we have.

**Comment by EwoutH** [comment]
I just compared the data from two runs on the same day.

It's likely solvable as it's a scraping problem and not a website problem.

**Comment by EwoutH** [comment]
It looks like #54 and #56 prove that the MSC v2 webscraper is deterministic. Since v2 will likely replace the original, I'm closing this for now.

CC @imvs95
