### ISSUE TITLE
Maersk notebook Pandas Dataframe

### ISSUE THREAD

**Issue by thomassandbergen** [EwoutH/shipping-data#38]
Put the output data in a Pandas Dataframe. Origin en Destination ports will be the most important information.

**Comment by EwoutH** [comment]
Let me know if you want an extra pair of eyes on this

**Comment by thomassandbergen** [comment]
> Let me know if you want an extra pair of eyes on this

Sure, will first try to put all data in a Dataframe. After that we can try to make it a bit more coherent and clear.

**Comment by thomassandbergen** [comment]
Finished a long time ago. Everything is currently in the dataframe.
